In [1]:
print('Hello world')

Hello world


In [2]:
!pip3 install numpy

/Users/yashrathore/.zshenv:1: command not found: Export


## we are going to learn numpy now!


### this is new headline

In [3]:
import numpy as np

In [33]:
arr = np.array([1, 2, 3])

In [34]:
type(arr)

numpy.ndarray

In [35]:
arr.ndim

1

In [36]:
arr.shape

(3,)

# In the above statement k andar arr.shape kiya toh output mein (3, ) jo aya hai waha one d array ko indicate karta hai 

In [39]:
arr.size

3

In [40]:
arr.dtype

dtype('int64')

In [41]:
#creating array from the list with type float
a=np.array([[1,2,3],[4, 2, 5]], dtype = 'float')
print("array created using passed list:\n",a)

array created using passed list:
 [[1. 2. 3.]
 [4. 2. 5.]]


In [46]:
c=np.zeros((3,4))

In [47]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
c.size

12

In [49]:
c.shape

(3, 4)

In [50]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

eye() identity matrix print karta hai


In [56]:
np.arange?

In [59]:
c=np.arange(0,30,5)
print("print the array from 0 to 30 with in 5 step: ",c)

print the array from 0 to 30 with in 5 step:  [ 0  5 10 15 20 25]


In [63]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [67]:
a=np.random.random((2,2))
print("print the random array:\n",a)

print the random array:
 [[0.15363168 0.34061115]
 [0.54972899 0.01303611]]


In [72]:
np.random.random((2,2))

array([[0.43002925, 0.89415459],
       [0.01244774, 0.98754192]])

In [73]:
#reshapping the array 3*4 into 2*2*3
arr=np.array([[1,2,4,6],
              [5,7,8,9],
              [3,5,7,8]])
new_arr=arr.reshape(2,2,3)

In [74]:
new_arr

array([[[1, 2, 4],
        [6, 5, 7]],

       [[8, 9, 3],
        [5, 7, 8]]])

In [75]:
#reshapping the array 3*4 into 4*3
arr1=np.array([[1,2,4,6],
              [5,7,8,9],
              [3,5,7,8]])
new_arr=arr1.reshape(4,3)

In [76]:
new_arr

array([[1, 2, 4],
       [6, 5, 7],
       [8, 9, 3],
       [5, 7, 8]])

In [77]:
#reshapping the array 3*4 into 2*2*3
arr=np.array([[1,2,4,6],
              [5,7,8,9],
              [3,5,7,8]])
new_arr=arr.reshape(3,7)
#This statement give me error because total 12 element but we want print 21 elements

ValueError: cannot reshape array of size 12 into shape (3,7)

In [90]:
arr=np.array([[1,2,4,6],
              [5,7,8,9],
              [3,5,7,8],
              [2,7,9,5]])

In [91]:
arr[1:4, 0:3]

array([[5, 7, 8],
       [3, 5, 7],
       [2, 7, 9]])

In [92]:
arr[1: , :3:2]

array([[5, 8],
       [3, 7],
       [2, 9]])

In [106]:
#bhaut important feature broadcasting feature
a=np.array([1,2,3,4])

In [107]:
a+1


array([2, 3, 4, 5])

In [108]:
print(a)

[1 2 3 4]


In [109]:
a*2

array([2, 4, 6, 8])

In [113]:
#transpose of the array
arr=np.array([[1,2,4,6],
              [5,7,8,9],
              [3,5,7,8]])
print("Print the array before the transpose:\n",arr)
print('Print the array after the transpose:\n',arr.T)

Print the array before the transpose:
 [[1 2 4 6]
 [5 7 8 9]
 [3 5 7 8]]
Print the array after the transpose:
 [[1 5 3]
 [2 7 5]
 [4 8 7]
 [6 9 8]]


In [118]:
#find the maximum element in the array
arr=np.array([[1,2,4,6],
              [5,7,8,9],
              [3,5,7,80]])
print('Print the maximum element in the array:\n',arr.max());
print("\n")
print('Print the maximum element in the row at 1:\n',arr.max(axis=0));

Print the maximum element in the array:
 80


Print the maximum element in the row at 1:
 [ 5  7  8 80]
